# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np
vec = np.zeros(100)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
vec = np.ones(100)
vec

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
vec = np.full(100, 3)
vec

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [7]:
A = np.arange(9).reshape(3,3)
A[[0,1]] = A[[1,0]]
A

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 6. Создать вектор со значениями от 10 до 100

In [9]:
vec = np.arange(10,101)
vec

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [13]:
vec = np.arange(101)
vec = vec[::-1]
vec

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1,   0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [15]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [18]:
vec = np.array([1,2,3,4,5])
vec1 = np.zeros(len(vec) + (len(vec)-1)*3, int)
vec1[::4] = vec
vec1

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 10. Создать 3x3 единичную матрицу

In [19]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [20]:
arr = np.random.random((3,3,3))
arr

array([[[0.54218992, 0.75256795, 0.69887794],
        [0.98592753, 0.4700534 , 0.02101308],
        [0.77867401, 0.83617998, 0.81098778]],

       [[0.50166285, 0.01150438, 0.545975  ],
        [0.61611094, 0.78813078, 0.92781696],
        [0.82173855, 0.25929958, 0.56846404]],

       [[0.38731328, 0.50606876, 0.9108939 ],
        [0.01451949, 0.15574318, 0.10977034],
        [0.96219681, 0.33622161, 0.64040835]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [29]:
arr = np.random.random((10,10))
arrmin, arrmax = arr.min(), arr.max()
print('min:', arrmin,',', 'max:', arrmax)

min: 0.00852902144986123 , max: 0.9999439770296527


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [31]:
vec = np.random.random(30)
avrg = vec.mean()
avrg

0.4624345257727125

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [34]:
A = np.ones((5,5))
A[1:-1,1:-1] = 0
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [43]:
A = np.ones((10,10))
A[2:-2,2:-2] = 3
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 3., 3., 3., 3., 3., 1., 1.],
       [1., 1., 3., 3., 3., 3., 3., 3., 1., 1.],
       [1., 1., 3., 3., 3., 3., 3., 3., 1., 1.],
       [1., 1., 3., 3., 3., 3., 3., 3., 1., 1.],
       [1., 1., 3., 3., 3., 3., 3., 3., 1., 1.],
       [1., 1., 3., 3., 3., 3., 3., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [47]:
A = np.diag(np.arange(1,5), k = -1)
A

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [49]:
A = np.zeros((8,8), dtype = int)
A[1::2, ::2] = 1
A[::2, 1::2] = 1
A

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [50]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [56]:
A = np.tile(np.array([[0,1],[1,0]]), (4,4))
A

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [57]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [59]:
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [63]:
A = np.zeros((5,5))
A += np.arange(5)
A

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [64]:
vec = np.linspace(0,1,12)[1:-1]
vec

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [65]:
c = np.random.random(10)
c.sort()
c

array([0.03188943, 0.35330808, 0.36116623, 0.36902833, 0.40021126,
       0.51083653, 0.57515892, 0.63835649, 0.90849503, 0.9113962 ])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [66]:
arr1 = np.random.randint(0,5,8)
arr2 = np.random.randint(0,5,8)
equal = np.allclose(arr1,arr2)
equal

False

#### 28. Сделать массив неизменяемым

In [73]:
s = np.arange(10)
s.flags.writeable = False
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 29. Найти n наибольших значений в массиве

In [75]:
s = np.arange(100)
np.random.shuffle(s)
n = 7
s[np.argpartition(-s,n)[:n]]


array([99, 93, 95, 94, 96, 98, 97])

#### 30. Заменить максимальный элемент на ноль

In [76]:
s = np.random.random((10))
s[s.argmax()] = 0
s

array([0.37402756, 0.63440136, 0.47880012, 0.29323175, 0.7683228 ,
       0.74768275, 0.52834729, 0.16917545, 0.49763898, 0.        ])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [77]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [78]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [80]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [81]:
arr = np.arange(100)
c = np.random.uniform(0,100)
i = (np.abs(arr-c)).argmin()
print(arr[i])

86


#### 36. Преобразовать массив из float в int

In [83]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

In [85]:
A = np.random.rand(5, 10)
S = A - A.mean(axis=1, keepdims=True)
S

array([[ 0.14175962,  0.20476892, -0.4565051 ,  0.29349495,  0.39844727,
         0.12249505, -0.30988802, -0.47081208, -0.14720041,  0.2234398 ],
       [-0.02716155,  0.23485469,  0.17374629, -0.29888649, -0.40603019,
         0.36176402,  0.16680277, -0.01635419, -0.19775417,  0.00901882],
       [ 0.09162916,  0.40166389,  0.12780776, -0.34585723, -0.32116333,
         0.15681593,  0.00756596, -0.23331657,  0.14829399, -0.03343956],
       [-0.21074929,  0.16938847,  0.20118657, -0.18004259,  0.24215674,
        -0.4154575 , -0.18190662,  0.04919589, -0.05375111,  0.37997944],
       [ 0.06595019, -0.10325326,  0.05016495, -0.07286247,  0.12583579,
         0.15277835, -0.12381537, -0.14954588,  0.08276996, -0.02802225]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [88]:
A = np.random.randint(0,20,(3,3))
print(A[A[:1].argsort()])

[[[ 4 15 13]
  [18  4  2]
  [16  7  7]]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям